HGV-783: Add new payment types.
HedvigInsurance/claims-service pull request #75
Opened 2021-02-01 14:04 UTC by Michael-Duivestein

# Jira Issue: [HVG-783]

## What?
- Added two new items to PaymentType: IndemnityCost and Expense.
- Added a unified endpoint and DTO for all payments to InternalController.
- Created PaymentRequestRouter to create the correct command for each payment type.
- For new payment types, added new commands and added new handlers to ClaimsAggregate.
- For new payment types, added new events and added new listeners to ClaimsEventListener.
- Removed unused field from PaymentAddedEvent.
- Updated readme.

## Testing:
- Tested new endpoint via Insomnia. 
- Manual, IndemnityCost, and Expense payments worked flawlessly.
- Commented out MemberSanctionStatus check as Meerkat is not running locally.

## Optional checklist
- [x] Codescouted
- [ ] Unit tests written
- [x] Tested locally

2021-02-01 14:05 UTC, Michael-Duivestein commented on src/main/java/com/hedvig/claims/aaafindahomeforme/PaymentRequestRouter.kt
> +package com.hedvig.claims.aaafindahomeforme
I need to find a home for this. Any suggestions?

2021-02-02 08:49 UTC, meletios commented on src/main/java/com/hedvig/claims/aaafindahomeforme/PaymentRequestRouter.kt
> +package com.hedvig.claims.aaafindahomeforme
An idea is to be under the services package, and rename it to PaymentRoutingService :D

2021-02-02 09:27 UTC, meletios requested changes
Nice, i have one important question about removing the attribute from the event though. It is related on how Axon works.

2021-02-02 09:27 UTC, meletios commented on src/main/java/com/hedvig/claims/aggregates/ClaimsAggregate.java
> +import com.hedvig.claims.events.PaymentAddedEvent;
❤️

2021-02-02 09:31 UTC, vonElfvin reviewed
I think this is great! 

My suggestions to consider before we merge:
1. The return types based on outcome
2. The reporting projection for payments to take these ones into account
3. Codescout some minor stuff that you can see in the comments

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/aaafindahomeforme/PaymentRequestRouter.kt
> +    }
Separate class for this one pls

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/aaafindahomeforme/PaymentRequestRouter.kt
> +package com.hedvig.claims.aaafindahomeforme
"payments" maybe?

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/aaafindahomeforme/PaymentRequestRouter.kt
> +        commandBus.sendAndWait<Any>(command)
```suggestion
        commandBus.sendAndWait<Void>(AddPaymentCommand(
            UUID.randomUUID().toString(),
            createPaymentDto.claimId,
            LocalDateTime.now(),
            createPaymentDto.amount.number.doubleValueExact(),
            createPaymentDto.deductible.number.doubleValueExact(),
            createPaymentDto.note,
            createPaymentDto.exGratia,
            createPaymentDto.handlerReference
        ))
```

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/aaafindahomeforme/PaymentRequestRouter.kt
> +        commandBus.sendAndWait<Any>(command)
```suggestion
        commandBus.sendAndWait<Void>(AddIndemnityCostPaymentCommand(
            UUID.randomUUID().toString(),
            createPaymentDto.claimId,
            LocalDateTime.now(),
            createPaymentDto.amount,
            createPaymentDto.deductible,
            createPaymentDto.note,
            createPaymentDto.exGratia,
            createPaymentDto.handlerReference
        ))
```

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/aaafindahomeforme/PaymentRequestRouter.kt
> +        NO_CONTENT,
So ACCEPTED is for automatic and NO_CONTENT is for manual/the others? Maybe we should just have a "COMPLETED", "FORBIDDEN", "MEMBER_NOT_FOUND" and "CLAIM_NOT_FOUND" and return the appropriate result in the controller instead. We have full control of the return type in back-office anyways

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/aggregates/ClaimsAggregate.java
> -import com.hedvig.claims.events.*;
Neat 😍

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/commands/AddExpensePaymentCommand.kt
> +    @TargetAggregateIdentifier var claimID: String,
```suggestion
    @TargetAggregateIdentifier var claimId: String,
```

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/aggregates/ClaimsAggregate.java
> +        apply(pe);
May as well 🤷 
```suggestion
        apply(new IndemnityCostPaymentAddedEvent(
            cmd.getId(),
            cmd.getClaimID(),
            cmd.getDate(),
            this.userId,
            cmd.getAmount(),
            cmd.getDeductible(),
            cmd.getNote(),
            cmd.getExGratia(),
            cmd.getHandlerReference()
        ));
```

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/commands/AddExpensePaymentCommand.kt
> +    var handlerReference: String?
Should probable be `val` here

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/commands/AddIndemnityCostPaymentCommand.kt
> +data class AddIndemnityCostPaymentCommand(
Same fixes here as above

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/events/IndemnityCostPaymentAddedEvent.kt
> +class IndemnityCostPaymentAddedEvent (
`val`

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/query/ClaimsEventListener.java
> +        Payment p = new Payment();
```suggestion
        Payment payment = new Payment();
```

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/query/ClaimsEventListener.java
> +    public void on(IndemnityCostPaymentAddedEvent e, @Timestamp Instant timestamp) {
```suggestion
    public void on(IndemnityCostPaymentAddedEvent event, @Timestamp Instant timestamp) {
```

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/query/ClaimsEventListener.java
> +        Event ev = createEvent(e, String.format(
```suggestion
        Event claimEvent = createEvent(e, String.format(
```

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/query/ClaimsEventListener.java
> +            "A manual indemnity cost payment (%s) was executed. The amount is %s \nThe payment was added by %s on %s",
```suggestion
            "A indemnity cost payment (%s) was executed. The amount is %s \nThe payment was added by %s on %s",
```

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/web/InternalController.kt
> +            PaymentRequestRouter.CommandCreationStatus.NOT_FOUND -> ResponseEntity.notFound().build<Void>()
```suggestion
        return when (paymentRequestRouter.routePayment(createPaymentDto)) {
            CreatePayoutOutcome.COMPLETED -> ResponseEntity.noContent().build()
            CreatePayoutOutcome.MEMBER_NOT_FOUND,
            CreatePayoutOutcome.CLAIM_NOT_FOUND -> ResponseStatus.notFound().build()
            CreatePayoutOutcome.FORBIDDEN -> ResponseEntity.forbidden().build()
```

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/query/ClaimsEventListener.java
> +    @EventSourcingHandler
Even though `@EventSourcingHandler` works since it's the same as `@EventHandler` the appropriate is to use `@EventSourcingHandler` for the `Aggregate` and `@EventHandler` for the projections. So maybe do some codescouting in here and change all `@EventSourcingHandler` -> `@EventHandler`

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/web/InternalController.kt
> +    fun addClaimPayment(@RequestBody createPaymentDto: CreatePaymentDto): ResponseEntity<*> {
```suggestion
    fun addClaimPayment(@RequestBody createPaymentDto: CreatePaymentDto): ResponseEntity<Void> {
```

2021-02-02 09:31 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/aaafindahomeforme/PaymentRequestRouter.kt
> +class PaymentRequestRouter(
To align a bit with how we usually name these things 🤷 
```suggestion
@Service
class ClaimPaymentService(
```

2021-02-02 09:32 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/events/PaymentAddedEvent.java
> -  LocalDateTime payoutDate;
No we do not since this one has historically always been null :)

2021-02-02 09:36 UTC, Michael-Duivestein commented on src/main/java/com/hedvig/claims/aaafindahomeforme/PaymentRequestRouter.kt
> +package com.hedvig.claims.aaafindahomeforme
Changed to com.hedvig.claims.payments.PaymentRoutingService

2021-02-02 10:12 UTC, Michael-Duivestein commented on src/main/java/com/hedvig/claims/web/InternalController.kt
> +            PaymentRequestRouter.CommandCreationStatus.NOT_FOUND -> ResponseEntity.notFound().build<Void>()
`ResponseEntity.forbidden()` does not exist.

2021-02-03 08:23 UTC, AlexSJ1990 approved these changes
Looks great!

2021-02-03 08:23 UTC, AlexSJ1990 commented on src/main/java/com/hedvig/claims/query/ClaimsEventListener.java
> +    @EventHandler
🧹

2021-02-03 08:32 UTC, vonElfvin approved these changes

2021-02-03 08:32 UTC, vonElfvin commented on src/main/java/com/hedvig/claims/web/InternalController.kt
> +            CreatePaymentOutcome.FORBIDDEN -> ResponseEntity.status(HttpStatus.FORBIDDEN).build<Void>()
```suggestion
            CreatePaymentOutcome.FORBIDDEN -> ResponseEntity.status(HttpStatus.FORBIDDEN).build()
```

2021-02-04 08:15 UTC, meletios approved these changes
Cool, 2 very small, tiny questions.

2021-02-04 08:15 UTC, meletios commented on src/main/java/com/hedvig/claims/aggregates/ClaimsAggregate.java
> +        payment.payoutDate = null;
🤔 Did you remove payoutdate right?

2021-02-04 08:15 UTC, meletios commented on src/main/java/com/hedvig/claims/aggregates/ClaimsAggregate.java
> +        payment.payoutDate = null;
🤔

2021-02-04 08:15 UTC, meletios commented on src/main/java/com/hedvig/claims/web/dto/PaymentDTO.java
> +    this.amount = Money.of(amount, "SEK");
Is it always SEK though?

2021-02-04 08:18 UTC, Michael-Duivestein commented on src/main/java/com/hedvig/claims/web/dto/PaymentDTO.java
> +    this.amount = Money.of(amount, "SEK");
Yes. It's hard-coded everywhere. :(
Changing it would be a completely new feature that touches a lot of areas.

2021-02-04 08:18 UTC, Michael-Duivestein commented on src/main/java/com/hedvig/claims/aggregates/ClaimsAggregate.java
> +        payment.payoutDate = null;
Good point! I can remove it from the commands. Will not touch the events though.

2021-02-04 08:19 UTC, Michael-Duivestein commented on src/main/java/com/hedvig/claims/aggregates/ClaimsAggregate.java
> +        payment.payoutDate = null;
This is an event. What happens if I remove it from there? Will it affect past events?

2021-02-05 10:02 UTC, meletios reviewed
Double the upcaster again

2021-02-08 10:39 UTC, meletios approved these changes
Not sure if we need to use Sweden's timezone. But since its something minor, feel free to merge

2021-02-08 10:39 UTC, meletios commented on src/main/java/com/hedvig/claims/query/ClaimsEventListener.java
> +        payment.date = LocalDateTime.ofInstant(timestamp, UTC);
```suggestion
        payment.date = LocalDateTime.ofInstant(timestamp, SWEDEN_TZ);
```

2021-02-08 10:39 UTC, meletios commented on src/main/java/com/hedvig/claims/query/ClaimsEventListener.java
> +        payment.date = LocalDateTime.ofInstant(timestamp, UTC);
```suggestion
        payment.date = LocalDateTime.ofInstant(timestamp, SWEDEN_TZ);
```

2021-02-08 10:39 UTC, meletios commented on src/main/java/com/hedvig/claims/query/ClaimsEventListener.java
> +        payment.date = LocalDateTime.ofInstant(timestamp, UTC);
```suggestion
        payment.date = LocalDateTime.ofInstant(timestamp, SWEDEN_TZ);
```

2021-02-08 10:42 UTC, Michael-Duivestein commented on src/main/java/com/hedvig/claims/query/ClaimsEventListener.java
> +        payment.date = LocalDateTime.ofInstant(timestamp, UTC);
Times in the DB must be in UTC.

2021-02-08 12:24 UTC, merged