added swish payout to AutomaticPayment
HedvigInsurance/claims-service pull request #84
Opened 2021-02-19 12:00 UTC by FredrikAreschoug

## What?
- added swish payout to AutomaticPayment

## Why?
- Swish!

## Optional checklist
- [ ] Codescouted
- [x] Unit tests written
- [ ] Tested locally

2021-02-19 12:03 UTC, AlexSJ1990 approved these changes
Looks really nice!

2021-02-19 13:58 UTC, Michael-Duivestein requested changes

2021-02-19 13:58 UTC, Michael-Duivestein commented on src/main/java/com/hedvig/claims/web/InternalController.kt
> +            SelectedPayoutDetails.NotSelected
This method is deprecated, unused, and about to be removed. Please modify `InternalController.addClaimPayment()`  and it's associated Dtos instead.

2021-02-19 14:02 UTC, FredrikAreschoug commented on src/main/java/com/hedvig/claims/web/InternalController.kt
> +            SelectedPayoutDetails.NotSelected
I have but on line 78 of `ClaimPaymentService` this is just because I need to send in something so it defaults to `NotSelected`

2021-03-10 08:20 UTC, Michael-Duivestein approved these changes

2021-03-17 11:13 UTC, AlexSJ1990 approved these changes
✌️

2021-03-17 11:13 UTC, AlexSJ1990 commented on src/main/java/com/hedvig/homer/handlers/SpeechToTextServiceImpl.kt
> +import kotlin.jvm.Throws
do we need this?

2021-03-17 11:58 UTC, FredrikAreschoug commented on src/main/java/com/hedvig/homer/handlers/SpeechToTextServiceImpl.kt
> +import kotlin.jvm.Throws
Good catch no my computer is acting up and I need this to run the service. I will remove it!

2021-03-17 15:49 UTC, merged